---
title: 'DS 2020 - Homework #1'
author: "Your Name"
date: "`r Sys.Date()`"
format: 
    html:
        embed-resources: true
---

```{r} 
#| label: setup
#| purl: false
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```

## Asking good questions

Asking good questions is a valuable skill to have. Asking questions in an online setting is both easier and harder than asking questions in person; we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

* stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

* R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

* [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)


Follow these links and read through the advice given, then complete the following:

* **Download the Quarto file with these homework instructions to use as a template for your work.
Make sure to replace "Your Name" in the YAML with your name.**

* **Pick one question from stackoverflow and identify a minimum of three way(s) in which it is not asked well by completing these steps:**

    1. **(1 point)** Which question did you pick (link to it).

    1. **(1 point)** Take a screenshot (or take a picture with your phone). Make sure to place the image in the same folder as your `qmd` file  and include it in your Quarto file. You can use the syntax for links above as an example.

    1. **(3 points)** Relate the readings to how the question is phrased. For that, write a paragraph on what a good question should do and then state what the stackoverflow question does. Identify at least three shortcomings.

    1. **(3 points)** Re-phrase the question to make it better. You can use placeholders for information that is not given in the original question, e.g. "version" or "platform".
 

**Note**: **(2 points)** Make sure that your submission is fully reproducible, i.e., the TA and I will 'knit' your submission in Quarto. Including any links to files is the tricky part here. Make sure that you don't use any file structure that depends on your computing environment.


For the submission: submit a zipped file solution that includes the Quarto file, image file, and HTML file.


